networks:
  frontend:
  backend:

services:

  nginx:
    image: nginx:1.25
    container_name: lemp-nginx
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - frontend
      - backend

  php:
    image: php:8.2-fpm
    container_name: lemp-php
    volumes:
      - ./app:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.3
    container_name: lemp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: lemp-phpmyadmin
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  db_data:
